Added Dracula Theme
kurmachu/retro-docs-site pull request #10
Opened 2022-11-21 07:41 UTC by woooferz

Yes i added another very epic theme!

2022-11-21 08:24 UTC, no1crate reviewed
Very good! I'll personally suggest that you change the font color at the lang menu, I don't know if it's my computer but it's unreadable.
- Crate

2022-11-21 13:55 UTC, kurmachu requested changes

2022-11-21 13:55 UTC, kurmachu commented on themes/dark/dracula.css
> +/* [THEME META] {"ver":1, "author":"woooferz", "description":"Dracula Theme (pretty cool)", "accessibility":"optimized"} */
> Accessibility optimized themes are reviewed to a higher standard than the default accessibility level. They should be free of all accessibility issues (up to AAA) on all states (hover, active, etc).

This theme does not meet the requirements for optimized accessibility. Please check all your contrast ratios towards [the WebAIM guidelines](https://webaim.org/resources/contrastchecker/), or opt-out back to standard accessibility.

```suggestion
/* [THEME META] {"ver":1, "author":"woooferz", "description":"Dracula Theme (pretty cool)"} */
```

ℹ️ A standard accessibility test was not performed due to issues detected with optimized accessibility.

2022-11-22 06:38 UTC, kurmachu approved these changes
Contrast ratio checks passed successfully.

2022-11-22 06:38 UTC, merged